apiVersion: v1
data:
  DATABASE_NAME: Ym9vdGNhbXBfZGI=
  DATABASE_HOST: MTczLjI0OS40NC4yNg==
  DATABASE_PASSWORD: cG9zdGdyZXM=
  DATABASE_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  name: backend-secrets
  namespace: bootcamp
